### ISSUE TITLE
make `itk.ants_registration` have the same API and behavior as `ants.registration`

### ISSUE THREAD

**Issue by thewtex** [thewtex/ANTsWasm#2]
Ref: https://antspyx.readthedocs.io/en/latest/registration.html

The wrapping of itk.ANTSRegistration, `itk.ants_registration`, should have a similar API and behavior as antspy `ants.registration`.

First add tests following the ANTs tests for just all the C++ interfaces, options and behavior.

Then add the corresponding Python tests.

**Comment by dzenanz** [comment]
Which ANTs files should we include and invoke from https://github.com/thewtex/ANTsWasm/blob/main/include/itkANTSRegistration.hxx? There are many abstraction layers in ANTs. [ANTsPy code](https://github.com/ANTsX/ANTsPy/blob/aa29ee8a27bb82b2d684dd14df810b3c5c82e4d0/ants/registration/interface.py#L1342-L1342) is not helpful there.

**Comment by dzenanz** [comment]
My WIP is coming up with:
```log
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindANTS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ANTS", but
  CMake did not find one.

  Could not find a package configuration file provided by "ANTS" with any of
  the following names:

    ANTSConfig.cmake
    ants-config.cmake
```
The easiest path forward seems to be to resolve https://github.com/ANTsX/ANTs/issues/1369.

**Comment by dzenanz** [comment]
With main running into:
```log
itkANTSRegistration: warning(4): ITK type not wrapped, or currently not known: itk::DataObjectDecorator< itk::CompositeTransform< double, 2 > >
itkANTSRegistration: warning(4): ITK type not wrapped, or currently not known: itk::DataObjectDecorator< itk::CompositeTransform< double, 3 > >
```
